### ISSUE TITLE
Q: Do you accept contributions? 

### ISSUE THREAD

**Issue by bagobor** [ApoorvaJ/Papaya#6]
I'm porting Papaya to OSX right now (+ some fixes).
Will you accept it? Should I preserve "c-only" code style?

**Comment by ApoorvaJ** [comment]
Firstly, thanks a ton for expressing interest in this. I really appreciate it.

That being said, I'd seriously recommend you wait a month or so, before porting. I'm currently thoroughly changing the OpenGL system, downgrading from requiring OpenGL 3.2, to only requiring OpenGL 1.4 + some extensions. I'd feel bad about wasting your time if you started porting right now.

I am actively working towards a v0.1 release build. That build will be a good candidate to port to OSX. If you could wait a bit, I'll be sure to drop you an email once that milestone build is out and ready to port.

I currently won't accept pull requests on an OSX build, because I don't have a Mac, and hence no way to test it. I am definitely open to pointing to your repository in the readme, once it's stable for milestone releases.

As for the coding style, Papaya has a clearly defined application-platform boundary. You should only have to write the platform-specific code, and application code should just work out of the box. If it doesn't feel free to open issues on this repository - I'd be happy to look at them. Check out win32_papaya.cpp and linux_papaya.cpp for platform-specific code, and how it interacts with papaya.cpp, which is the application code.

**Comment by bagobor** [comment]
I have plans to finish OSX port today + I'll add GLFW for cross platform OpenGL/Window handing. + premake script to generate build scripts for windows/osx/linux.

**Comment by ApoorvaJ** [comment]
I'm making major changes to the OpenGL code as we speak. Just fair warning. Of course, feel free to change anything and everything. This is why I've licensed the whole project under an open license.

Have fun, and good luck with your port. :)

**Comment by bagobor** [comment]
btw I'm done with premake5 config for windows. :package:

**Comment by bagobor** [comment]
i'm done with premake and windows build. All is working + fixes.
Let me know if you'll accept my fork.
OSX port is halted as premake5 fails to generate XCode files...

**Comment by bagobor** [comment]
latest premake Alpha fixed problem! (builded from source...)
It's too late here, so I'll continue tomorrow ^)

**Comment by ApoorvaJ** [comment]
It's cool that you're experimenting with Papaya, but I won't be merging your branch in. I'm avoiding build systems and middleware platforms like GLFW.

**Comment by bagobor** [comment]
I see ) no problem. 
I have personal interest to use it as some kind of playground.

**Comment by ApoorvaJ** [comment]
Thank you for understanding. Feel free to drop me an email any time, if you have questions.
